-- Generated from the Teams example sample data. Do not edit by hand.
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a1', 0, 'Peter Parker', 'PP', 'red', 'mention', 'Avengers Tower › Mission Briefings', 'mentioned you in Avengers Tower › Mission Briefings', 'Can you review the Mark 85 flight plan before the 2 PM briefing?', '9:42 AM', 1, 2, 0);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a2', 1, 'Maria Hill', 'MH', 'blue', 'reply', 'S.H.I.E.L.D. Helicarrier › Command', 'replied to your post in S.H.I.E.L.D. Helicarrier › Command', 'The orbital traffic numbers hold up, I added the Queens sector split.', '9:18 AM', 1, 0, 0);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a3', 2, 'Shuri', 'SH', 'purple', 'reaction', 'Wakanda R&D › Vibranium Allocations', 'reacted to your message in Wakanda R&D › Vibranium Allocations', 'Love the allocation plan, the sonic dampeners are a smart add.', '8:57 AM', 1, 1, 0);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a4', 3, 'Sam Wilson', 'SW', 'teal', 'follow', 'Avengers Compound › Training', 'started following Avengers Compound › Training', 'You will now see new posts from this channel.', '8:31 AM', 0, 0, 0);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a5', 4, 'Bruce Banner', 'BB', 'green', 'reply', 'Stark Industries › Suit Lab', 'replied to your comment in Stark Industries › Suit Lab', 'The vibranium weave held through the drop test, see the telemetry.', '8:05 AM', 0, 3, 1);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a6', 5, 'Steve Rogers', 'SR', 'blue', 'mention', 'Avengers Compound › Training', 'mentioned you in Avengers Compound › Training', 'The training roster is on slide 12 of the briefing deck.', '7:48 AM', 0, 0, 0);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a7', 6, 'Natasha Romanoff', 'NR', 'red', 'reply', 'Avengers Tower › Mission Briefings', 'replied to your thread in Avengers Tower › Mission Briefings', 'Agreed, let us keep the strike team small for now.', 'Yesterday', 0, 2, 1);
INSERT INTO activity_items (id, position, actor, initials, color, kind, place, text, preview, time, unread, replies, replied) VALUES ('a8', 7, 'Thor', 'TH', 'gold', 'reaction', 'Asgard › Observatory', 'reacted to your file in Asgard › Observatory', 'The Bifrost readings are exactly what we needed.', 'Yesterday', 0, 0, 0);
INSERT INTO activity_state (id, filter, active) VALUES (1, 'all', '');
