-- Generated from the Teams example sample data. Do not edit by hand.
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e16', 0, 0, 'Avengers daily standup', '9:00 AM', '15 min', 'blue', 'Avengers Tower 42', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e17', 0, 1, 'Mark 85 suit diagnostics', '10:30 AM', '45 min', 'violet', 'Stark Industries R&D', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e18', 0, 2, '1:1 with Bruce Banner', '1:00 PM', '30 min', 'green', 'Avengers Compound', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e19', 0, 3, 'Wakanda vibranium sync', '2:30 PM', '45 min', 'orange', 'Wakanda Lab 3', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e20', 0, 4, 'Briefing with Nick Fury', '11:00 AM', '60 min', 'violet', 'S.H.I.E.L.D. Helicarrier', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e21', 0, 5, 'Web shooters with Peter Parker', '3:30 PM', '45 min', 'blue', 'Queens', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e22', 1, 0, 'Avengers daily standup', '9:00 AM', '15 min', 'blue', 'Avengers Tower 42', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e23', 1, 1, 'Suit test with Shuri', '10:00 AM', '90 min', 'orange', 'Wakanda Lab 3', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e24', 1, 2, '1:1 with Pepper Potts', '2:00 PM', '30 min', 'green', 'Avengers Tower 42', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e25', 1, 3, 'Guardians uplink window', '11:00 AM', '60 min', 'blue', 'Knowhere uplink', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e26', 1, 4, 'Stark budget review - Q3', '8:30 AM', '60 min', 'red', 'Stark Industries R&D', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e27', 1, 5, 'Interview - Riri Williams', '10:00 AM', '30 min', 'violet', 'Avengers Compound', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e28', 2, 0, 'Avengers daily standup', '9:00 AM', '15 min', 'blue', 'Avengers Tower 42', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e29', 2, 1, 'Mission briefing with Maria Hill', '11:00 AM', '60 min', 'violet', 'S.H.I.E.L.D. Helicarrier', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e30', 2, 2, 'Wanda and the Westview report', '9:30 AM', '45 min', 'orange', 'Sanctum Sanctorum', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e31', 2, 3, '1:1 with Natasha Romanoff', '1:30 PM', '30 min', 'green', 'Avengers Compound', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e32', 2, 4, 'Vibranium allocation review', '2:00 PM', '90 min', 'red', 'Wakanda Lab 3', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e33', 2, 5, 'S.H.I.E.L.D. debrief', '3:00 PM', '45 min', 'green', 'S.H.I.E.L.D. Helicarrier', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e1', 3, 0, 'Avengers daily standup', '9:00 AM', '15 min', 'blue', 'Avengers Tower 42', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e2', 3, 1, 'Suit diagnostics with Shuri', '10:30 AM', '45 min', 'violet', 'Wakanda Lab 3', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e3', 3, 2, '1:1 with Sam Wilson', '1:00 PM', '30 min', 'green', 'Avengers Compound', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e4', 3, 3, 'Sanctum consult with Doctor Strange', '9:30 AM', '30 min', 'blue', 'Sanctum Sanctorum', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e5', 3, 4, 'Asgard observatory briefing', '2:30 PM', '45 min', 'orange', 'Asgard observatory', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e6', 3, 5, 'S.H.I.E.L.D. mission briefing', '11:00 AM', '60 min', 'violet', 'S.H.I.E.L.D. Helicarrier', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e7', 3, 6, 'Web shooter bug triage', '3:00 PM', '30 min', 'red', 'Queens', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e8', 3, 7, 'Guardians uplink check', '4:00 PM', '30 min', 'orange', 'Knowhere uplink', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e9', 4, 0, 'Press and gala prep with Pepper Potts', '9:00 AM', '45 min', 'violet', 'Avengers Tower 42', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e10', 4, 1, 'Phase 6 roadmap review', '11:00 AM', '60 min', 'blue', 'Stark Industries R&D', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e11', 4, 2, 'Suit design workshop with Shuri', '10:00 AM', '90 min', 'orange', 'Wakanda Lab 3', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e12', 4, 3, '1:1 with James Rhodes', '9:30 AM', '30 min', 'green', 'Avengers Compound', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e13', 4, 4, 'Recruiting panel - Kate Bishop', '2:00 PM', '45 min', 'red', 'Avengers Tower 42', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e14', 4, 5, 'S.H.I.E.L.D. debrief', '11:30 AM', '45 min', 'red', 'S.H.I.E.L.D. Helicarrier', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e15', 4, 6, 'Suit demo Friday', '3:30 PM', '45 min', 'blue', 'Stark Industries R&D', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e34', 5, 0, 'Avengers daily standup', '9:00 AM', '15 min', 'blue', 'Avengers Tower 42', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e35', 5, 1, 'Wakanda stealth suit review', '11:00 AM', '45 min', 'violet', 'Wakanda Lab 3', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e36', 5, 2, '1:1 with Peter Parker', '9:30 AM', '30 min', 'green', 'Queens', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e37', 5, 3, 'Westview anomaly follow-up', '1:00 PM', '45 min', 'orange', 'Sanctum Sanctorum', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e38', 5, 4, 'Operation planning with Maria Hill', '11:00 AM', '60 min', 'violet', 'S.H.I.E.L.D. Helicarrier', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e39', 5, 5, 'Shawarma Friday', '3:00 PM', '45 min', 'red', 'Avengers Tower 42', 4);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e40', 6, 0, 'Avengers all-hands', '9:00 AM', '45 min', 'violet', 'Avengers Compound', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e41', 6, 1, 'Stark budget review - FY27', '11:00 AM', '60 min', 'red', 'Stark Industries R&D', 0);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e42', 6, 2, 'Avengers daily standup', '9:00 AM', '15 min', 'blue', 'Avengers Tower 42', 1);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e43', 6, 3, 'Web shooter workshop with Peter Parker', '10:00 AM', '90 min', 'orange', 'Queens', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e44', 6, 4, '1:1 with Carol Danvers', '2:00 PM', '30 min', 'green', 'Avengers Tower 42', 2);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e45', 6, 5, 'Sanctum consult with Wong', '2:00 PM', '45 min', 'orange', 'Sanctum Sanctorum', 3);
INSERT INTO calendar_events (id, week, position, title, time, dur, color, location, day) VALUES ('e46', 6, 6, 'Mark 85 flight demo', '3:30 PM', '45 min', 'blue', 'Stark Industries R&D', 4);
INSERT INTO calendar_state (id, week, selected) VALUES (1, 3, '');
