-- Generated from the Teams example sample data. Do not edit by hand.
INSERT INTO teams (id, position, name, initials, color, expanded) VALUES ('avengers', 0, 'Avengers', 'AV', 'red', 1);
INSERT INTO teams (id, position, name, initials, color, expanded) VALUES ('wakanda', 1, 'Wakanda R&D', 'WK', 'purple', 0);
INSERT INTO teams (id, position, name, initials, color, expanded) VALUES ('shield', 2, 'S.H.I.E.L.D. Ops', 'SH', 'blue', 0);
INSERT INTO teams (id, position, name, initials, color, expanded) VALUES ('stark', 3, 'Stark Industries', 'SI', 'gold', 0);
INSERT INTO teams (id, position, name, initials, color, expanded) VALUES ('guardians', 4, 'Guardians', 'GD', 'teal', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('av-general', 'avengers', 0, 'General', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('av-missions', 'avengers', 1, 'Missions', 3);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('av-suitlab', 'avengers', 2, 'Suit Lab', 1);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('gd-general', 'guardians', 0, 'General', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('gd-milano', 'guardians', 1, 'Milano', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('sh-general', 'shield', 0, 'General', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('sh-briefings', 'shield', 1, 'Briefings', 1);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('st-general', 'stark', 0, 'General', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('st-rd', 'stark', 1, 'R&D', 4);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('wk-general', 'wakanda', 0, 'General', 0);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('wk-vibranium', 'wakanda', 1, 'Vibranium', 2);
INSERT INTO channels (id, team_id, position, name, unread) VALUES ('wk-outreach', 'wakanda', 2, 'Outreach', 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('av1', 'av-general', 0, 'Steve Rogers', 'SR', 'blue', '9:30 AM', 'Weekly debrief moves to Friday', 'Debrief at 4 PM in the war room. Bring field notes and one lesson learned.', 1, 8, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('av2', 'av-general', 1, 'Robert Downey Jr.', 'RDJ', 'red', '8:45 AM', 'Shawarma Friday returns', 'Reserved the corner table for Friday at 1 PM. Sign up in the thread.', 0, 6, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('avm1', 'av-missions', 0, 'Nick Fury', 'NF', 'gray', 'Yesterday', 'Mission log: Zurich drop', 'Extraction window opened at 0300. All agents accounted for, cargo secured.', 0, 7, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('avm2', 'av-missions', 1, 'Natasha Romanoff', 'NR', 'red', 'Mon', 'Next extraction window', 'The next window is Thursday 0200 to 0400. Assign roles by Wednesday.', 0, 4, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('avs1', 'av-suitlab', 0, 'Robert Downey Jr.', 'RDJ', 'red', 'Yesterday', 'Mark LXXXV thruster test', 'Twelve seconds of hover at 92 percent power. Telemetry is in the shared drive.', 1, 9, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('avs2', 'av-suitlab', 1, 'Bruce Banner', 'BB', 'green', 'Mon', 'Nano-lattice stress test', 'The new lattice held under triple load. Full report is on the lab bench.', 0, 5, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('gd1', 'gd-general', 0, 'Thor', 'TH', 'gold', '9:25 AM', 'Milano docked for repairs', 'The Guardians'' ship is in the Asgard hangar. Rocket found a cracked coolant line.', 0, 6, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('gd2', 'gd-general', 1, 'Carol Danvers', 'CD', 'gold', 'Yesterday', 'Refuel window at Knowhere', 'The Milano gets a refuel window at Knowhere on Saturday. Two hours only.', 0, 4, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('gdm1', 'gd-milano', 0, 'Thor', 'TH', 'gold', 'Yesterday', 'Jump point coordinates', 'Charting a new jump point past Titan. The numbers are pinned to the board.', 1, 5, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('gdm2', 'gd-milano', 1, 'Carol Danvers', 'CD', 'gold', 'Mon', 'Cargo manifest for the relief run', 'The Milano carries grain and medicine to the outer colonies this run.', 0, 6, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('shb1', 'sh-briefings', 0, 'Nick Fury', 'NF', 'gray', 'Yesterday', 'Briefing: Loki sighting in Oslo', 'Satellite caught a green flare over Oslo. Thor confirms it is not friendly.', 1, 7, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('shb2', 'sh-briefings', 1, 'Maria Hill', 'MH', 'blue', 'Mon', 'Clearance updates', 'Level seven clearances renew this week. Submit the forms before Thursday.', 0, 4, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('sh1', 'sh-general', 0, 'Nick Fury', 'NF', 'gray', '9:00 AM', 'Helicarrier maintenance window', 'Bay three is down for turbine work until Thursday. Route all quinjets to bay two.', 1, 5, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('sh2', 'sh-general', 1, 'Maria Hill', 'MH', 'blue', 'Yesterday', 'Ops roster for November', 'The November roster is posted. Swap requests are due by Friday noon.', 0, 3, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('st1', 'st-general', 0, 'Pepper Potts', 'PP', 'pink', '9:15 AM', 'Quarterly town hall', 'Town hall is Wednesday at 10 AM. Send questions to the thread by Tuesday.', 1, 7, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('st2', 'st-general', 1, 'Happy Hogan', 'HH', 'orange', 'Yesterday', 'Security badge refresh', 'New badges arrive Friday. The old ones stop working at 6 PM sharp.', 0, 4, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('str1', 'st-rd', 0, 'Robert Downey Jr.', 'RDJ', 'red', 'Yesterday', 'Repulsor efficiency up 12 percent', 'The new nozzle ring gave us a 12 percent gain on the test stand.', 1, 10, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('str2', 'st-rd', 1, 'Bruce Banner', 'BB', 'green', 'Mon', 'Arc reactor thermal run', 'Ran the reactor at full load for six hours. Coils stayed inside spec.', 0, 7, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('wk1', 'wk-general', 0, 'Shuri', 'SH', 'purple', '9:05 AM', 'Kimoyo diagnostics update', 'The new bead firmware halves sync time. Rolling out to the lab today.', 1, 8, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('wk2', 'wk-general', 1, 'T''Challa', 'TC', 'violet', 'Yesterday', 'Outreach summit in Geneva', 'Wakanda speaks at the Geneva summit next month. Draft the panels by Friday.', 0, 6, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('wko1', 'wk-outreach', 0, 'T''Challa', 'TC', 'violet', 'Yesterday', 'Relief run to Port-au-Prince', 'Two flyers leave Friday with medical supplies. Manifest is in the thread.', 1, 9, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('wko2', 'wk-outreach', 1, 'Shuri', 'SH', 'purple', 'Mon', 'School lab kits shipped', 'Five hundred lab kits left the workshop this morning. Tracking is live.', 0, 6, 0);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('wkv1', 'wk-vibranium', 0, 'Shuri', 'SH', 'purple', 'Yesterday', 'Vibranium yield this week', 'Six kilograms from the north mine, all above grade. Charts are posted.', 0, 7, 1);
INSERT INTO posts (id, channel_id, position, author, initials, color, time, subject, text, pinned, likes, liked) VALUES ('wkv2', 'wk-vibranium', 1, 'Okoye', 'OK', 'orange', 'Mon', 'Shipment security drill', 'Drill runs Thursday at dawn. Two decoy convoys, one real route.', 0, 4, 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av1-r1', 'av1', 0, 'Natasha Romanoff', 'NR', 'red', '9:35 AM', 'I will bring the Zurich extraction notes.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av1-r2', 'av1', 1, 'Robert Downey Jr.', 'RDJ', 'red', '9:41 AM', 'Slides are ready. Five minutes per mission, tops.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av1-r3', 'av1', 2, 'Thor', 'TH', 'gold', '9:52 AM', 'I shall arrive after the Asgard relay check.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av1-r4', 'av1', 3, 'Bruce Banner', 'BB', 'green', '10:04 AM', 'The lab report is in the shared folder already.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av1-r5', 'av1', 4, 'Clint Barton', 'CB', 'purple', '10:12 AM', 'Can we keep one thread for open actions?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av2-r1', 'av2', 0, 'Pepper Potts', 'PP', 'pink', '8:50 AM', 'I put it on the tower calendar.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av2-r2', 'av2', 1, 'Happy Hogan', 'HH', 'orange', '8:58 AM', 'Table for twelve confirmed with the kitchen.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av2-r3', 'av2', 2, 'Wanda Maximoff', 'WM', 'pink', '9:10 AM', 'Count me in. Extra garlic sauce.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('av2-r4', 'av2', 3, 'Vision', 'VI', 'violet', '9:14 AM', 'I will attend for the conversation, not the meal.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm1-r1', 'avm1', 0, 'Natasha Romanoff', 'NR', 'red', 'Yesterday', 'Cover held. The safehouse was already empty.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm1-r2', 'avm1', 1, 'Clint Barton', 'CB', 'purple', 'Yesterday', 'No drones on the roof, so the roof route worked.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm1-r3', 'avm1', 2, 'Sam Wilson', 'SW', 'teal', 'Yesterday', 'Air cover logged two unknown radar sweeps.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm1-r4', 'avm1', 3, 'Steve Rogers', 'SR', 'blue', '8:20 AM', 'Good run. Debrief notes go to the vault tonight.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm2-r1', 'avm2', 0, 'Clint Barton', 'CB', 'purple', 'Mon', 'I can take overwatch on the east ridge.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm2-r2', 'avm2', 1, 'Wanda Maximoff', 'WM', 'pink', 'Mon', 'I will hold the perimeter if the lights fail.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm2-r3', 'avm2', 2, 'Thor', 'TH', 'gold', '8:05 AM', 'Should the Bifrost be a backup exit?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avm2-r4', 'avm2', 3, 'Maria Hill', 'MH', 'blue', '8:30 AM', 'Yes, but only if the tunnel floods again.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs1-r1', 'avs1', 0, 'Bruce Banner', 'BB', 'green', 'Yesterday', 'Thermal margins look safe at that burn rate.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs1-r2', 'avs1', 1, 'Peter Parker', 'PP', 'red', 'Yesterday', 'The stabilizers barely wobbled on the replay.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs1-r3', 'avs1', 2, 'James Rhodes', 'JR', 'gray', 'Yesterday', 'I want that thruster pair on the War Machine frame.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs1-r4', 'avs1', 3, 'Shuri', 'SH', 'purple', '8:10 AM', 'Try the vibranium dampeners on the ankle joints.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs2-r1', 'avs2', 0, 'Robert Downey Jr.', 'RDJ', 'red', 'Mon', 'Then we shave two kilos off the chest plate.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs2-r2', 'avs2', 1, 'Shuri', 'SH', 'purple', 'Mon', 'Send me the sample. I will run it against vibranium weave.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs2-r3', 'avs2', 2, 'Peter Parker', 'PP', 'red', 'Mon', 'Can I watch the next test after school?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('avs2-r4', 'avs2', 3, 'Happy Hogan', 'HH', 'orange', '8:40 AM', 'Only if the lab insurance form is signed first.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd1-r1', 'gd1', 0, 'Carol Danvers', 'CD', 'gold', '9:30 AM', 'I can tow parts from the lunar depot.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd1-r2', 'gd1', 1, 'Peter Parker', 'PP', 'red', '9:44 AM', 'Is Groot growing in the cargo bay again?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd1-r3', 'gd1', 2, 'Thor', 'TH', 'gold', '9:58 AM', 'Yes. He has claimed the starboard corner.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd1-r4', 'gd1', 3, 'Sam Wilson', 'SW', 'teal', '10:10 AM', 'Sounds like my old apartment.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd2-r1', 'gd2', 0, 'Thor', 'TH', 'gold', 'Yesterday', 'I shall escort the cargo myself.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd2-r2', 'gd2', 1, 'Nick Fury', 'NF', 'gray', 'Yesterday', 'Keep the manifest logged with S.H.I.E.L.D.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd2-r3', 'gd2', 2, 'Stephen Strange', 'SS', 'gray', 'Yesterday', 'The nearest jump point shifts at dusk.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gd2-r4', 'gd2', 3, 'Wanda Maximoff', 'WM', 'pink', '8:05 AM', 'I can steady the hull if the clamps fail.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm1-r1', 'gdm1', 0, 'Carol Danvers', 'CD', 'gold', 'Yesterday', 'Ran the route twice. It is stable enough.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm1-r2', 'gdm1', 1, 'Stephen Strange', 'SS', 'gray', 'Yesterday', 'I will anchor the far side with the Sanctum.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm1-r3', 'gdm1', 2, 'Peter Parker', 'PP', 'red', 'Yesterday', 'The math needs one more check on the drift.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm1-r4', 'gdm1', 3, 'Nick Fury', 'NF', 'gray', '8:15 AM', 'Log every jump. We are not losing another ship.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm2-r1', 'gdm2', 0, 'Thor', 'TH', 'gold', 'Mon', 'The hold is full. Even the secret compartment.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm2-r2', 'gdm2', 1, 'Sam Wilson', 'SW', 'teal', 'Mon', 'The relief coordinators sent updated drop points.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm2-r3', 'gdm2', 2, 'Shuri', 'SH', 'purple', 'Mon', 'Water purifiers are loaded and sealed.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('gdm2-r4', 'gdm2', 3, 'Robert Downey Jr.', 'RDJ', 'red', '8:40 AM', 'Fuel cells are on the tower. Do not fly dry.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh1-r1', 'sh1', 0, 'Maria Hill', 'MH', 'blue', '9:08 AM', 'I moved the flight schedule to the board.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh1-r2', 'sh1', 1, 'Carol Danvers', 'CD', 'gold', '9:20 AM', 'I can cover the orbital watch meanwhile.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh1-r3', 'sh1', 2, 'Robert Downey Jr.', 'RDJ', 'red', '9:34 AM', 'Stark Industries sends the turbine parts tonight.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh1-r4', 'sh1', 3, 'Sam Wilson', 'SW', 'teal', '9:47 AM', 'Bay two needs a fuel top-up before Friday.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh2-r1', 'sh2', 0, 'Nick Fury', 'NF', 'gray', 'Yesterday', 'Keep two agents on the night watch at all times.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh2-r2', 'sh2', 1, 'Clint Barton', 'CB', 'purple', 'Yesterday', 'I will take the Thanksgiving week shift.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh2-r3', 'sh2', 2, 'Natasha Romanoff', 'NR', 'red', 'Yesterday', 'Swap me to the early shift after Tuesday.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('sh2-r4', 'sh2', 3, 'Carol Danvers', 'CD', 'gold', '8:10 AM', 'Approved. I signed the updated sheet.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb1-r1', 'shb1', 0, 'Thor', 'TH', 'gold', 'Yesterday', 'It is a decoy. My brother is already off world.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb1-r2', 'shb1', 1, 'Stephen Strange', 'SS', 'gray', 'Yesterday', 'The Sanctum sees no gate activity near Oslo.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb1-r3', 'shb1', 2, 'Wanda Maximoff', 'WM', 'pink', 'Yesterday', 'I felt a spell echo, but it faded fast.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb1-r4', 'shb1', 3, 'Maria Hill', 'MH', 'blue', '8:12 AM', 'Standing the alert down to level two.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb2-r1', 'shb2', 0, 'Nick Fury', 'NF', 'gray', 'Mon', 'No exceptions this cycle, even for the Avengers.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb2-r2', 'shb2', 1, 'Carol Danvers', 'CD', 'gold', 'Mon', 'Mine is already in. Space duty needs the access.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb2-r3', 'shb2', 2, 'Clint Barton', 'CB', 'purple', 'Mon', 'Forms done. Can I get the range access back?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('shb2-r4', 'shb2', 3, 'Robert Downey Jr.', 'RDJ', 'red', '8:30 AM', 'Sent mine by courier. Paper is safer, apparently.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st1-r1', 'st1', 0, 'Happy Hogan', 'HH', 'orange', '9:20 AM', 'The auditorium is booked and the coffee is ordered.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st1-r2', 'st1', 1, 'Robert Downey Jr.', 'RDJ', 'red', '9:30 AM', 'I will demo the repulsor rig at the end.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st1-r3', 'st1', 2, 'James Rhodes', 'JR', 'gray', '9:42 AM', 'Keep the demo indoors this time.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st1-r4', 'st1', 3, 'Maria Hill', 'MH', 'blue', '9:55 AM', 'Can the town hall stream to the DC office?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st2-r1', 'st2', 0, 'Pepper Potts', 'PP', 'pink', 'Yesterday', 'The interns get theirs at the front desk.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st2-r2', 'st2', 1, 'Robert Downey Jr.', 'RDJ', 'red', 'Yesterday', 'Mine should just open everything, thanks.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st2-r3', 'st2', 2, 'Peter Parker', 'PP', 'red', 'Yesterday', 'Can the lab interns keep the after-hours badge?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('st2-r4', 'st2', 3, 'James Rhodes', 'JR', 'gray', '8:25 AM', 'Only with a signed mentor form. Ask Happy.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str1-r1', 'str1', 0, 'Bruce Banner', 'BB', 'green', 'Yesterday', 'The plasma curve stayed clean the whole run.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str1-r2', 'str1', 1, 'Shuri', 'SH', 'purple', 'Yesterday', 'Vibranium lining would hold that curve longer.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str1-r3', 'str1', 2, 'Peter Parker', 'PP', 'red', 'Yesterday', 'I ran the math on the paper. It checks out.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str1-r4', 'str1', 3, 'James Rhodes', 'JR', 'gray', '8:10 AM', 'Then the War Machine retrofit moves up a month.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str1-r5', 'str1', 4, 'Vision', 'VI', 'violet', '8:26 AM', 'I logged the harmonics for the next build.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str2-r1', 'str2', 0, 'Robert Downey Jr.', 'RDJ', 'red', 'Mon', 'Good. I want a second run with the older coils.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str2-r2', 'str2', 1, 'Shuri', 'SH', 'purple', 'Mon', 'Send me the cooling data. I have an idea.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str2-r3', 'str2', 2, 'Vision', 'VI', 'violet', 'Mon', 'The second run is on the schedule for Friday.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('str2-r4', 'str2', 3, 'Peter Parker', 'PP', 'red', 'Mon', 'Can I take the readings for the Friday run?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk1-r1', 'wk1', 0, 'T''Challa', 'TC', 'violet', '9:10 AM', 'The council will appreciate the faster briefings.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk1-r2', 'wk1', 1, 'Okoye', 'OK', 'orange', '9:22 AM', 'The Dora Milaje need the update before the border drill.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk1-r3', 'wk1', 2, 'Robert Downey Jr.', 'RDJ', 'red', '9:35 AM', 'Can the beads link to the tower network?', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk1-r4', 'wk1', 3, 'Bruce Banner', 'BB', 'green', '9:48 AM', 'I will mirror the protocol in the lab this week.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk2-r1', 'wk2', 0, 'Shuri', 'SH', 'purple', 'Yesterday', 'I will present the water purifier pilot data.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk2-r2', 'wk2', 1, 'Okoye', 'OK', 'orange', 'Yesterday', 'Security plan is ready. Two routes, one decoy.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk2-r3', 'wk2', 2, 'Maria Hill', 'MH', 'blue', '8:20 AM', 'S.H.I.E.L.D. can share the venue maps.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wk2-r4', 'wk2', 3, 'Sam Wilson', 'SW', 'teal', '8:44 AM', 'Count me in for the relief logistics panel.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko1-r1', 'wko1', 0, 'Shuri', 'SH', 'purple', 'Yesterday', 'Water filters are packed and calibrated.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko1-r2', 'wko1', 1, 'Sam Wilson', 'SW', 'teal', 'Yesterday', 'I can escort the second flyer personally.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko1-r3', 'wko1', 2, 'Robert Downey Jr.', 'RDJ', 'red', 'Yesterday', 'The tower covered the fuel cost. Receipts to Pepper.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko1-r4', 'wko1', 3, 'Okoye', 'OK', 'orange', '8:15 AM', 'Landing clearance is confirmed for both ships.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko2-r1', 'wko2', 0, 'T''Challa', 'TC', 'violet', 'Mon', 'The teachers will get the lesson plans too.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko2-r2', 'wko2', 1, 'Okoye', 'OK', 'orange', 'Mon', 'Customs paperwork cleared without a hold.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko2-r3', 'wko2', 2, 'Peter Parker', 'PP', 'red', 'Mon', 'Midtown High would love a kit for the science club.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wko2-r4', 'wko2', 3, 'Bruce Banner', 'BB', 'green', '8:05 AM', 'Add a radiation badge to each kit. Safety first.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv1-r1', 'wkv1', 0, 'T''Challa', 'TC', 'violet', 'Yesterday', 'Route the surplus to the medical wing first.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv1-r2', 'wkv1', 1, 'Okoye', 'OK', 'orange', 'Yesterday', 'Mine security found a tunnel. We sealed it.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv1-r3', 'wkv1', 2, 'Bruce Banner', 'BB', 'green', 'Yesterday', 'I would like a sample for the lattice test.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv1-r4', 'wkv1', 3, 'Robert Downey Jr.', 'RDJ', 'red', '8:25 AM', 'The suit dampeners need two grams, no more.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv2-r1', 'wkv2', 0, 'Shuri', 'SH', 'purple', 'Mon', 'I added trackers to all three crates.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv2-r2', 'wkv2', 1, 'T''Challa', 'TC', 'violet', 'Mon', 'The river route stays open as the third option.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv2-r3', 'wkv2', 2, 'Natasha Romanoff', 'NR', 'red', 'Mon', 'I can send the stealth checklist we used in Zurich.', 0);
INSERT INTO replies (id, post_id, position, author, initials, color, time, text, own) VALUES ('wkv2-r4', 'wkv2', 3, 'Clint Barton', 'CB', 'purple', '8:55 AM', 'Happy to ride shotgun on the decoy run.', 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('av1', 0, '❤️', 4, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('av1', 1, '😂', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('av2', 0, '😍', 5, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('av2', 1, '😊', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('av2', 2, '😂', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avm1', 0, '😮', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avm1', 1, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avm2', 0, '❤️', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avm2', 1, '😢', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avs1', 0, '😮', 4, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avs1', 1, '❤️', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avs2', 0, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avs2', 1, '😊', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('avs2', 2, '😮', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gd1', 0, '😂', 5, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gd1', 1, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gd2', 0, '😮', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gd2', 1, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gdm1', 0, '😮', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gdm1', 1, '❤️', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gdm2', 0, '😍', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('gdm2', 1, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('sh1', 0, '😮', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('sh1', 1, '❤️', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('sh2', 0, '❤️', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('sh2', 1, '😊', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('shb1', 0, '😮', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('shb1', 1, '😂', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('shb2', 0, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('shb2', 1, '😢', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('st1', 0, '❤️', 4, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('st1', 1, '😊', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('st2', 0, '😂', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('st2', 1, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('str1', 0, '😮', 4, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('str1', 1, '❤️', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('str1', 2, '😂', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('str2', 0, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('str2', 1, '😮', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wk1', 0, '❤️', 4, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wk1', 1, '😮', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wk2', 0, '😍', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wk2', 1, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wko1', 0, '😍', 4, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wko1', 1, '❤️', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wko2', 0, '❤️', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wko2', 1, '😊', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wkv1', 0, '😮', 3, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wkv1', 1, '😂', 1, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wkv2', 0, '❤️', 2, 0);
INSERT INTO reactions (post_id, position, emoji, count, mine) VALUES ('wkv2', 1, '😮', 1, 0);
INSERT INTO channel_files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f1', 0, 'Mark LXXXV schematic.pdf', 'pdf', '', 'PDF', 'Today, 9:12 AM', 'Robert Downey Jr.', '8.2 MB', '', 0, 0, 0);
INSERT INTO channel_files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f2', 1, 'Vibranium yield report.xlsx', 'xls', '', 'X', 'Yesterday', 'Shuri', '1.1 MB', '', 0, 0, 0);
INSERT INTO channel_files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f3', 2, 'Mission log Zurich.docx', 'doc', '', 'W', 'Yesterday', 'Natasha Romanoff', '640 KB', '', 0, 0, 1);
INSERT INTO channel_files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f4', 3, 'Arc reactor diagnostics.pptx', 'ppt', '', 'P', 'Oct 1', 'Bruce Banner', '12 MB', '', 0, 0, 0);
INSERT INTO channel_files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f5', 4, 'Suit lab test data.zip', 'zip', '', 'ZIP', 'Sep 28', 'Peter Parker', '24 MB', '', 0, 0, 0);
INSERT INTO channel_state (id, team, channel, tab) VALUES (1, 'avengers', 'av-general', 'posts');
