-- Generated from the Teams example sample data. Do not edit by hand.
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f1', 0, 'Avengers roster.docx', 'doc', 'W', 'Word document', 'Today, 9:14 AM', 'Steve Rogers', '32 KB', 'Avengers Tower', 1, 0, 1);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f2', 1, 'Vibranium supply.xlsx', 'xls', 'X', 'Excel workbook', 'Today, 8:47 AM', 'Shuri', '156 KB', 'Wakanda R&D', 1, 0, 0);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f3', 2, 'Mark VII schematics.pdf', 'pdf', 'PDF', 'PDF document', 'Yesterday, 4:02 PM', 'Robert Downey Jr.', '6.8 MB', 'Stark Industries', 0, 1, 1);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f4', 3, 'Wakanda outreach deck.pptx', 'ppt', 'P', 'PowerPoint presentation', 'Yesterday, 1:36 PM', 'T''Challa', '3.4 MB', 'Wakanda R&D', 1, 1, 0);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f5', 4, 'Sanctum ward notes.docx', 'doc', 'W', 'Word document', 'Oct 2, 11:20 AM', 'Stephen Strange', '44 KB', 'Sanctum', 0, 0, 0);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f6', 5, 'Web shooter firmware.zip', 'zip', 'ZIP', 'Zip archive', 'Oct 2, 9:05 AM', 'Peter Parker', '128 MB', 'Stark Industries', 0, 1, 1);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f7', 6, 'Suit paint samples.png', 'img', 'IMG', 'PNG image', 'Oct 1, 5:41 PM', 'Pepper Potts', '2.2 MB', 'Stark Industries', 0, 1, 0);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f8', 7, 'Guardians flight log.txt', 'generic', 'FILE', 'Text file', 'Oct 1, 2:18 PM', 'Peter Quill', '780 KB', 'Knowhere', 1, 0, 0);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f9', 8, 'Stark gala guest list.xlsx', 'xls', 'X', 'Excel workbook', 'Sep 30, 10:02 AM', 'Happy Hogan', '61 KB', 'Stark Industries', 0, 0, 0);
INSERT INTO files (id, position, name, badge, badge_text, kind, modified, modified_by, size, location, team, shared, starred) VALUES ('f10', 9, 'Sokovia relief plan.pdf', 'pdf', 'PDF', 'PDF document', 'Sep 29, 3:24 PM', 'Maria Hill', '1.4 MB', 'S.H.I.E.L.D.', 1, 1, 0);
INSERT INTO files_state (id, filter, active) VALUES (1, 'recent', '');
