package files

// sample is the read-only file table every Default clones. Rows are in
// recency order, so the recent filter keeps table order.
var sample = []File{
	{"f1", "Avengers roster.docx", "doc", "W", "Word document",
		"Today, 9:14 AM", "Steve Rogers", "32 KB",
		"Avengers Tower", true, false, true},
	{"f2", "Vibranium supply.xlsx", "xls", "X", "Excel workbook",
		"Today, 8:47 AM", "Shuri", "156 KB",
		"Wakanda R&D", true, false, false},
	{"f3", "Mark VII schematics.pdf", "pdf", "PDF", "PDF document",
		"Yesterday, 4:02 PM", "Robert Downey Jr.", "6.8 MB",
		"Stark Industries", false, true, true},
	{"f4", "Wakanda outreach deck.pptx", "ppt", "P", "PowerPoint presentation",
		"Yesterday, 1:36 PM", "T'Challa", "3.4 MB",
		"Wakanda R&D", true, true, false},
	{"f5", "Sanctum ward notes.docx", "doc", "W", "Word document",
		"Oct 2, 11:20 AM", "Stephen Strange", "44 KB",
		"Sanctum", false, false, false},
	{"f6", "Web shooter firmware.zip", "zip", "ZIP", "Zip archive",
		"Oct 2, 9:05 AM", "Peter Parker", "128 MB",
		"Stark Industries", false, true, true},
	{"f7", "Suit paint samples.png", "img", "IMG", "PNG image",
		"Oct 1, 5:41 PM", "Pepper Potts", "2.2 MB",
		"Stark Industries", false, true, false},
	{"f8", "Guardians flight log.txt", "generic", "FILE", "Text file",
		"Oct 1, 2:18 PM", "Peter Quill", "780 KB",
		"Knowhere", true, false, false},
	{"f9", "Stark gala guest list.xlsx", "xls", "X", "Excel workbook",
		"Sep 30, 10:02 AM", "Happy Hogan", "61 KB",
		"Stark Industries", false, false, false},
	{"f10", "Sokovia relief plan.pdf", "pdf", "PDF", "PDF document",
		"Sep 29, 3:24 PM", "Maria Hill", "1.4 MB",
		"S.H.I.E.L.D.", true, true, false},
}
