apply plugin: 'com.android.application'

android {
    namespace 'com.chinmaysawant.lgremote'
    compileSdk 34

    defaultConfig {
        applicationId "com.chinmaysawant.lgremote"
        minSdkVersion 28
        targetSdkVersion 34
        versionCode 1
        versionName '0.0.2'
        testInstrumentationRunner 'com.chinmaysawant.lgremote.AccessibilityRegression'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(':lgremote')
}
